# stages:
#   - test

# echo-test:
#   stage: test
#   script:
#     - echo "deniz turkmen "
#   tags:
#   - tag-name

stages:
  - Build

Build for Dockerfile:
  stage: Build
  # this job requires docker-in-docker
  tags:
    - devops-docker-1
  image: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest