stages:
  - test
  - build
  - deploy

# variables:
#   KUBE_SERVER: https://kubernetes.deniz.master.internal:6443
#   KUBE_TOKEN: KUBE_TOKEN

deploy:
  stage: deploy
  image: cylab/kubectl
  tags:
    - devops-docker-1
  before_script:
    # create the configuration (context) for our kubernetes cluster
    - kubectl config set-cluster deploy-cluster --server="$KUBE_SERVER" --insecure-skip-tls-verify
    - kubectl config set-credentials gitlab --token=$(echo $KUBE_TOKEN | base64 -d)
    - echo $KUBE_TOKEN
    - kubectl config set-context deploy-cluster --cluster=deploy-cluster --namespace=default --user=gitlab
    - kubectl config use-context deploy-cluster

  script:
    - echo $KUBE_SERVER
    - echo $KUBE_TOKEN
    - echo $KUBE_TOKEN | base64 -d 
    - kubectl get pods
    - envsubst < deploy.tmpl > deploy.yaml
    - echo deploy.yaml
    - kubectl apply -f deploy.yaml