apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: denizyoutube/nginx:~v1.1
    argocd-image-updater.argoproj.io/api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: test-argocd
  project: default
  source:
    repoURL: "https://github.com/dnztest/argocd-image-updater-poc.git"
    path: kustomize/overlays/dev
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true