apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-kustomize
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ArgoCD/6- Kustomize/overlays/dev
    repoURL: https://github.com/denizturkmen/Ci-cd-Full-Content-Notes.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true