# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: myjob1
  namespace: test-argocd
spec:
  selector:
    app: myjob
  type: NodePort
  ports:
  - name: myjob
    protocol: TCP
    port: 80
    targetPort: 50
    nodePort: 30002
---