apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-argocd
  namespace: test
  labels:
    app:  nginx-argocd
spec:
  selector:
    matchLabels:
      app: nginx-argocd
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx-argocd
    spec:
      containers:
      - name:  nginx-argocd
        image:  denizyoutube/nginx:v1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  nginx-argocd
      restartPolicy: Always