apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-private
  namespace: test-private
  labels:
    app:  nginx-private
spec:
  selector:
    matchLabels:
      app: nginx-private
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx-private
    spec:
      containers:
      - name:  nginx-private
        image: 21195831/my-app-image-private:v1.1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      # imagePullSecrets:
      # - name: regcred
        ports:
        - containerPort:  80
          name:  nginx-private
      restartPolicy: Always