apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-private
spec:
  selector:
    app: nginx-private
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 31525