apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}-1
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "nginx.name" . }}
    chart: {{ include "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "nginx.name" . }}
    release: {{ .Release.Name }}
