image: alpine

stages:
  - Sonarcheck
  - Build
  - Deployment


variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Docker build and push:
  image: docker
  services: 
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]  
  stage: Build
  script:
    - echo "Starting docker image build and push"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  # when: manual
  tags:
    - devops-docker-1
  only:
    - main
  

Deployment for Test Env:
  image: ubuntu:20.04
  stage: Deployment
  tags:
    - deployment
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh 
    - apt-get -yqq install sshpass
    - apt-get install gettext-base 
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
  script:
    - envsubst < deployment/docker-compose-template-test.yml > deployment/docker-compose-test.yml
    - sshpass -p $pass ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gitlab@192.168.1.10 "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - sshpass -p $pass scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r deployment/docker-compose-test.yml gitlab@192.168.1.10:/home/gitlab/deployment/test/ 
    - sshpass -p $pass ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gitlab@192.168.1.10 "cd /home/gitlab/deployment/test/ && docker-compose -f docker-compose-test.yml pull"
    - sshpass -p $pass ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gitlab@192.168.1.10 "cd /home/gitlab/deployment/test/ && docker-compose -f docker-compose-test.yml stop web-site" 
    - sshpass -p $pass ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gitlab@192.168.1.10 "cd /home/gitlab/deployment/test/ && docker-compose -f docker-compose-test.yml rm -f web-site" 
    - sshpass -p $pass ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null gitlab@192.168.1.10 "cd /home/gitlab/deployment/test/ && docker-compose -f docker-compose-test.yml up -d"                     
  tags:
    - devops-docker-1
  only:
    - main
  environment:
    name: production
    url: http://192.168.1.10

# deployment-docker:
#   stage: deployment
#   # tags:
#   # - shell-runner 
#   script:
#     - echo "Docker Deployment basliyor...."
#     - docker login -u=$dhubusername -p=$dhubpassword
#     - docker pull denizturkmen/frontend-ci-cd:$CI_COMMIT_SHORT_SHA
#     - docker container rm -f dockerdeployment 
#     - docker run --name dockerdeployment --detach --publish 8082:80 denizturkmen/frontend-ci-cd:$CI_COMMIT_SHORT_SHA    
#   # when: manual
#   only:
#     - master
  
