apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/topahadzi/app
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/api.pull-secret: pullsecret:argocd/github-pull
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  project: default
  source:
    repoURL: "https://github.com/denizturkmen/Ci-cd-Full-Content-Notes.git"
    path: ArgoCD/3- Image Updater/gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true