apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  project: default
  source:
    repoURL: "https://github.com/denizturkmen/Ci-cd-Full-Content-Notes.git"
    path: ArgoCD/3- Image Updater/gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true