apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-custom-helm-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      valueFiles:
        - values.yaml
    path: ArgoCD/5- Helm/1- Custom Helm Template
    repoURL: 'https://github.com/denizturkmen/Ci-cd-Full-Content-Notes.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---